version: "3.9"

services:
  backend:
    build: ./backend
    container_name: csv-ollama_fastapi
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: csv-ollama_nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
